spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers:
      - localhost:40991

  cloud:
    stream:
      function:
        definition: orderBuy;orderSell
      bindings:
        orderBuy-out-0:
          destination: order.buy
        orderSell-out-0:
          destination: order.sell
      kafka:
        bindings:
          orderBuy-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.LongSerializer
          orderSell-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.LongSerializer
  output:
    ansi:
      enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

